### ISSUE TITLE
NDB put is working async

### ISSUE THREAD

**Issue by kautilya-pro** [GoogleCloudPlatform/datastore-ndb-python#285]
when I'm putting a new entity in ndb table and counting the number of all entities in the table. I'm getting one number lesser than what actually should be.
The put() is working asynchronously. Then, what's the difference between put() and put_async()?

**Comment by kolinko** [comment]
You might want to read about strong and eventual consistency. Regular put is synchronous, but the db change may have not arrived in the database yet for reading.

**Comment by wsh** [comment]
@kautilya-pro: assuming that by table you mean [kind](https://cloud.google.com/datastore/docs/concepts/entities#kinds_and_identifiers), the query you describe is a global query. As [this article on consistency in Cloud Datastore](https://cloud.google.com/datastore/docs/concepts/structuring_for_strong_consistency) notes:

> Global queries (those that do not execute against an entity group) are always eventually consistent.
