### ISSUE TITLE
Where is the new code?

### ISSUE THREAD

**Issue by SamuelMarks** [GoogleCloudPlatform/datastore-ndb-python#299]
https://pypi.org/project/google-cloud-ndb/ shows latest release as Nov 8, 2021 but all this code (any branch) has commits from 5 years ago
<img width="1228" alt="Screen Shot 2022-09-14 at 10 45 46 PM" src="https://user-images.githubusercontent.com/807580/190301718-fafe60f1-68e5-4336-b239-eb8a530f98c5.png">

My main interest in contribution is to get something that can run in a test environment outside of Google Cloud, like GitHub Actions, so I can test everything before deployment to GAE (or similar).

**Comment by snarfed** [comment]
New code is https://github.com/googleapis/python-ndb ! Sadly it's in maintenance mode, last real code change was Nov 2021, https://github.com/googleapis/python-ndb/issues/765, but it's totally usable outside Google Cloud. Example CI setup: https://app.circleci.com/pipelines/github/snarfed/granary , https://github.com/snarfed/granary/blob/main/.circleci/config.yml#L1

**Comment by anoteboom** [comment]
This would be the place:

https://github.com/googleapis/python-ndb

**Comment by SamuelMarks** [comment]
Thanks. Yeah I hear you, going to migrate to SQLalchemy soon: https://stackoverflow.com/questions/73751935/migrate-from-ndb-to-sqlalchemy#comment130421099_73833883

I'll try and open-source the code so as to help others migrate. One cool thing about the migration is it'll allow for local testing in very small instances (e.g., CI, or Dockerfile on alpine without Internet). Need to switch from webapp2 also 😅
